/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mcg.view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author alafaria
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setIconImage(getToolkit().createImage(getClass().getResource("/icones/icone_principal.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/imagens/telaPrincipal.png"));
        Image image = icon.getImage();
        painelPrincipal = new javax.swing.JLayeredPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCadastroUsuarios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCadastroPersonagem = new javax.swing.JMenuItem();
        menuCadastroClassePersonagem = new javax.swing.JMenuItem();
        menuCadastroRacaPersonagem = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuCadastrarMonstros = new javax.swing.JMenuItem();
        menuRolagemDados = new javax.swing.JMenu();
        MenuRolagemDados = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuCombate = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuAjuda = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Master Control Guide");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/user.png"))); // NOI18N
        jMenu1.setText("Usuários");

        menuCadastroUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastroUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cadusuario.png"))); // NOI18N
        menuCadastroUsuarios.setText("Cadastro de Usuários");
        menuCadastroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadastroUsuarios);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/personagem.png"))); // NOI18N
        jMenu2.setText("Personagens");

        menuCadastroPersonagem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastroPersonagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cadastrarPersonagem_32.png"))); // NOI18N
        menuCadastroPersonagem.setText("Cadastrar Personagem");
        menuCadastroPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroPersonagemActionPerformed(evt);
            }
        });
        jMenu2.add(menuCadastroPersonagem);

        menuCadastroClassePersonagem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastroClassePersonagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/classe_32.png"))); // NOI18N
        menuCadastroClassePersonagem.setText("Cadastrar Classe");
        menuCadastroClassePersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroClassePersonagemActionPerformed(evt);
            }
        });
        jMenu2.add(menuCadastroClassePersonagem);

        menuCadastroRacaPersonagem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastroRacaPersonagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/orc_32.png"))); // NOI18N
        menuCadastroRacaPersonagem.setText("Cadastrar Raça");
        menuCadastroRacaPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroRacaPersonagemActionPerformed(evt);
            }
        });
        jMenu2.add(menuCadastroRacaPersonagem);

        jMenuBar1.add(jMenu2);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/BeholderIcon48.png"))); // NOI18N
        jMenu5.setText("Monstros");

        menuCadastrarMonstros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastrarMonstros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/demi.png"))); // NOI18N
        menuCadastrarMonstros.setText("Cadastrar Monstros");
        menuCadastrarMonstros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarMonstrosActionPerformed(evt);
            }
        });
        jMenu5.add(menuCadastrarMonstros);

        jMenuBar1.add(jMenu5);

        menuRolagemDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/dice_48.png"))); // NOI18N
        menuRolagemDados.setText("Dados");
        menuRolagemDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRolagemDadosActionPerformed(evt);
            }
        });

        MenuRolagemDados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        MenuRolagemDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/dice.png"))); // NOI18N
        MenuRolagemDados.setText("Rolagem de Dados");
        MenuRolagemDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRolagemDadosActionPerformed(evt);
            }
        });
        menuRolagemDados.add(MenuRolagemDados);

        jMenuBar1.add(menuRolagemDados);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/combate.png"))); // NOI18N
        jMenu4.setText("Combate");

        menuCombate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuCombate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/dano.png"))); // NOI18N
        menuCombate.setText("Combate");
        menuCombate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCombateActionPerformed(evt);
            }
        });
        jMenu4.add(menuCombate);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/nivelMonstros.png"))); // NOI18N
        jMenuItem1.setText("Nível de desafio dos Monstros");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sobre.png"))); // NOI18N
        jMenu3.setText("Ajuda");

        menuAjuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sobre2.png"))); // NOI18N
        menuAjuda.setText("Sobre");
        menuAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAjudaActionPerformed(evt);
            }
        });
        jMenu3.add(menuAjuda);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sair.png"))); // NOI18N
        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setVisible(true);
    }//GEN-LAST:event_formWindowActivated

    private void menuCadastroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroUsuariosActionPerformed
        // TODO add your handling code here:
        TelaUsuario telaUsuario = new TelaUsuario();
        telaUsuario.setVisible(true);
        telaUsuario.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuCadastroUsuariosActionPerformed

    private void menuCadastroClassePersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroClassePersonagemActionPerformed
        // TODO add your handling code here:
        TelaCadastrarClasse telaCadastrarClasse = new TelaCadastrarClasse();
        telaCadastrarClasse.setVisible(true);
        telaCadastrarClasse.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuCadastroClassePersonagemActionPerformed

    private void menuCadastroPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroPersonagemActionPerformed
        // TODO add your handling code here:
        TelaCadastroPersonagem telaCadastrarPersonagem = new TelaCadastroPersonagem();
        telaCadastrarPersonagem.setVisible(true);
        telaCadastrarPersonagem.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuCadastroPersonagemActionPerformed

    private void menuCadastroRacaPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroRacaPersonagemActionPerformed
        // TODO add your handling code here:
        TelaCadastrarRaca telaCadastroRaca = new TelaCadastrarRaca();
        telaCadastroRaca.setVisible(true);
        telaCadastroRaca.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuCadastroRacaPersonagemActionPerformed

    private void menuRolagemDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRolagemDadosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuRolagemDadosActionPerformed

    private void MenuRolagemDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRolagemDadosActionPerformed
        // TODO add your handling code here:
        TelaRolagemDados telaRolagemDados = new TelaRolagemDados();
        telaRolagemDados.setVisible(true);
        telaRolagemDados.setLocationRelativeTo(null);
    }//GEN-LAST:event_MenuRolagemDadosActionPerformed

    private void menuCombateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCombateActionPerformed
        // TODO add your handling code here:
        TelaCombate telaCombate = new TelaCombate();
        telaCombate.setVisible(true);
        telaCombate.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuCombateActionPerformed

    private void menuCadastrarMonstrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarMonstrosActionPerformed
        // TODO add your handling code here:
        TelaCadastroMonstros telaCadastroMonstros = new TelaCadastroMonstros();
        telaCadastroMonstros.setVisible(true);
        telaCadastroMonstros.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuCadastrarMonstrosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        TelaNivelDesafio telaNivelDesafio = new TelaNivelDesafio();
        telaNivelDesafio.setVisible(true);
        telaNivelDesafio.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAjudaActionPerformed
        // TODO add your handling code here:
        TelaSobre telaSobre = new TelaSobre();
        telaSobre.setVisible(true);
        telaSobre.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuAjudaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuRolagemDados;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem menuAjuda;
    private javax.swing.JMenuItem menuCadastrarMonstros;
    private javax.swing.JMenuItem menuCadastroClassePersonagem;
    private javax.swing.JMenuItem menuCadastroPersonagem;
    private javax.swing.JMenuItem menuCadastroRacaPersonagem;
    private javax.swing.JMenuItem menuCadastroUsuarios;
    private javax.swing.JMenuItem menuCombate;
    private javax.swing.JMenu menuRolagemDados;
    private javax.swing.JLayeredPane painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
