/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mcg.view;

import br.com.mcg.dao.RepositorioMonstroDao;
import br.com.mcg.model.RepositorioMonstros;
import br.com.mcg.tabelaDeModelos.TabelaModeloRepositorioMonstros;
import javax.swing.JOptionPane;

/**
 *
 * @author alafaria
 */
public class TelaCadastroMonstros extends javax.swing.JFrame {

    RepositorioMonstros repositorioMonstros = new RepositorioMonstros();
    RepositorioMonstroDao repositorioMonstroDao = new RepositorioMonstroDao();

    /**
     * Creates new form TelaCadastroMonstros
     */
    public TelaCadastroMonstros() {
        initComponents();
        setIconImage(getToolkit().createImage(getClass().getResource("/icones/icone_principal.png")));
        tabelaPesquisaMonstros.setModel(new TabelaModeloRepositorioMonstros(new RepositorioMonstroDao().listarMonstros()));
        btExcluir.setEnabled(false);
        btEditar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jTabbedMonstros = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIdentificador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomeMonstro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtPontosDeVida = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtClasseDeArmadura1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPontosDeVidaAtual = new javax.swing.JTextField();
        txtDeslocamento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNivelDesafio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtReferencia = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtPesquisarMonstrosPorNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPesquisaMonstros = new javax.swing.JTable();
        btCadastrar = new javax.swing.JButton();
        btLimparTela = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Master Control Guide - Cadastro de Monstros");

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setForeground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Monstros");

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setText("Sair");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 566, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton5)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedMonstros.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Identificador: ");

        txtIdentificador.setEditable(false);
        txtIdentificador.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Nome do Monstro:");

        txtNomeMonstro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Tipo do Monstro:");

        comboTipo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Aberração Miúda", "Aberração Pequena", "Aberração Média", "Aberração Grande", "Aberração Enorme", "Aberração Imensa", "Besta Miúda", "Besta Média", "Besta Grande", "Besta Enorme", "Besta Imensa", "Celestial Pequeno", "Celestial Médio", "Celestial Grande", "Celestial Enorme", "Celestial Imenso", "Constructo Miúdo", "Constructo Pequeno", "Constructo Médio", "Constructo Grande", "Constructo Enorme", "Constructo Imenso", "Corruptor Miúdo", "Corruptor Pequeno", "Corruptor Médio", "Corruptor Grande", "Corruptor Enorme", "Corruptor Imenso", "Dragão Miúdo", "Dragão Médio", "Dragão Grande", "Dragão Enorme", "Dragão Imenso", "Elemental Miúdo", "Elemental Pequeno", "Elemental Médio", "Elemental Grande", "Elemental Enorme", "Elemental Imenso", "Enxame Médio de bestas Miúdas", "Fada Miúda", "Fada Pequena", "Fada Média", "Fada Grande", "Fada Enorme", "Fada Imensa", "Gigante Grande", "Gigante Enorme", "Gigante Imenso", "Humanoide Miúdo", "Humanoide Pequeno", "Humanoide Médio", "Humanoide Grande", "Limo Miúdo", "Limo Pequeno", "Limo Grande", "Limo Enorme", "Limo Imenso", "Monstruosidade Miúda", "Monstruosidade Pequena", "Monstruosidade Média", "Monstruosidade Grande", "Monstruosidade Enorme", "Monstruosidade Imensa", "Morto-Vivo Miúdo", "Morto_vivo Pequeno", "Morto-Vivo Médio", "Morto-Vivo Grande", "Morto-Vivo Enorme", "Morto-Vivo Imenso", "Planta Miúda", "Planta Pequena", "Planta Média", "Planta Grande", "Planta Enorme", "Planta Imensa", " ", " ", " ", " " }));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Classe de Armadura:");

        txtPontosDeVida.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Pontos de Vida:");

        txtClasseDeArmadura1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Pontos de Vida Atual:");

        txtPontosDeVidaAtual.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        txtDeslocamento.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Deslocamento:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Nível de Desafio:");

        txtNivelDesafio.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Referência:");

        txtReferencia.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/zumbi.png"))); // NOI18N

        jLayeredPane1.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(28, 28, 28))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtDeslocamento, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtNivelDesafio))
                    .addComponent(txtNomeMonstro)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtPontosDeVida, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtPontosDeVidaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtReferencia)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtClasseDeArmadura1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNomeMonstro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtClasseDeArmadura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPontosDeVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtPontosDeVidaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtDeslocamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtNivelDesafio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLayeredPane1))
                .addContainerGap())
        );

        jTabbedMonstros.addTab("Cadastro Monstros", jPanel2);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pesquisar.png"))); // NOI18N
        jLabel11.setText("Consultar monstros:");

        txtPesquisarMonstrosPorNome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtPesquisarMonstrosPorNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarMonstrosPorNomeKeyPressed(evt);
            }
        });

        tabelaPesquisaMonstros.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tabelaPesquisaMonstros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaPesquisaMonstros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPesquisaMonstrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPesquisaMonstros);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtPesquisarMonstrosPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtPesquisarMonstrosPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedMonstros.addTab("Consulta de Monstros", jPanel3);

        btCadastrar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/salvar.png"))); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btLimparTela.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btLimparTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/limparCampos.png"))); // NOI18N
        btLimparTela.setText("Limpar Tela");
        btLimparTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparTelaActionPerformed(evt);
            }
        });

        btEditar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/editar.png"))); // NOI18N
        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/excluir_1.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sair.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedMonstros, javax.swing.GroupLayout.PREFERRED_SIZE, 1069, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btLimparTela)
                        .addGap(18, 18, 18)
                        .addComponent(btCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(btEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btSair)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btCadastrar, btEditar, btExcluir, btLimparTela, btSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedMonstros, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimparTela)
                    .addComponent(btCadastrar)
                    .addComponent(btEditar)
                    .addComponent(btExcluir)
                    .addComponent(btSair))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btCadastrar, btEditar, btExcluir, btLimparTela, btSair});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:
        if (txtNomeMonstro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Nome não pode estar em branco!","Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (comboTipo.getSelectedItem().equals("Selecionar")) {
            JOptionPane.showMessageDialog(null, "Campo Tipo precisa ter um valor válido!","Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (txtClasseDeArmadura1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Classe de Armadura não pode estar em branco!","Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (txtPontosDeVida.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Pontos de Vida não pode estar em branco!","Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (txtPontosDeVidaAtual.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Pontos de Vida Atual não pode estar em branco!","Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (txtDeslocamento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Deslocamento não pode estar em branco!","Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (txtNivelDesafio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Nível de Desafio não pode estar em branco!","Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            repositorioMonstros.setNomeMonstro(txtNomeMonstro.getText());
            repositorioMonstros.setTipo((String) comboTipo.getSelectedItem());
            repositorioMonstros.setClasseDeArmadura(Integer.parseInt(txtClasseDeArmadura1.getText()));
            repositorioMonstros.setPontosDeVida(txtPontosDeVida.getText());
            repositorioMonstros.setPontosDeVidaAtual(Integer.parseInt(txtPontosDeVidaAtual.getText()));
            repositorioMonstros.setDeslocamento(txtDeslocamento.getText());
            repositorioMonstros.setNivelDeDesafio(txtNivelDesafio.getText());
            repositorioMonstros.setReferencia(txtReferencia.getText());
            repositorioMonstros.setSituacao("Em Combate");

            repositorioMonstroDao.adicionarMonstro(repositorioMonstros);
        }
        atualizarTabela();
        limparCampos();

    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btLimparTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparTelaActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_btLimparTelaActionPerformed

    private void tabelaPesquisaMonstrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPesquisaMonstrosMouseClicked
        // TODO add your handling code here:
        jTabbedMonstros.setSelectedIndex(0);
        txtIdentificador.setText(tabelaPesquisaMonstros.getValueAt(tabelaPesquisaMonstros.getSelectedRow(), TabelaModeloRepositorioMonstros.COLUNA_ID_REPOSITORIO_MONSTROS).toString());
        txtNomeMonstro.setText(tabelaPesquisaMonstros.getValueAt(tabelaPesquisaMonstros.getSelectedRow(), TabelaModeloRepositorioMonstros.COLUNA_NOME_MONTROS).toString());
        comboTipo.setSelectedItem(tabelaPesquisaMonstros.getValueAt(tabelaPesquisaMonstros.getSelectedRow(), TabelaModeloRepositorioMonstros.COLUNA_TIPO_MONTROS).toString());
        txtClasseDeArmadura1.setText(tabelaPesquisaMonstros.getValueAt(tabelaPesquisaMonstros.getSelectedRow(), TabelaModeloRepositorioMonstros.COLUNA_CLASSE_DE_ARMADURA_MONTROS).toString());
        txtPontosDeVida.setText(tabelaPesquisaMonstros.getValueAt(tabelaPesquisaMonstros.getSelectedRow(), TabelaModeloRepositorioMonstros.COLUNA_PONTOS_DE_VIDA_MONTROS).toString());
        txtPontosDeVidaAtual.setText(tabelaPesquisaMonstros.getValueAt(tabelaPesquisaMonstros.getSelectedRow(), TabelaModeloRepositorioMonstros.COLUNA_PONTOS_DE_VIDA_ATUAL_MONTROS).toString());
        txtDeslocamento.setText(tabelaPesquisaMonstros.getValueAt(tabelaPesquisaMonstros.getSelectedRow(), TabelaModeloRepositorioMonstros.COLUNA_DESLOCAMENTO_MONTROS).toString());
        txtNivelDesafio.setText(tabelaPesquisaMonstros.getValueAt(tabelaPesquisaMonstros.getSelectedRow(), TabelaModeloRepositorioMonstros.COLUNA_NIVEL_DE_DESAFIO_MONTROS).toString());
        txtReferencia.setText(tabelaPesquisaMonstros.getValueAt(tabelaPesquisaMonstros.getSelectedRow(), TabelaModeloRepositorioMonstros.COLUNA_REFERENCIA_MONTROS).toString());
        btExcluir.setEnabled(true);
        btEditar.setEnabled(true);
    }//GEN-LAST:event_tabelaPesquisaMonstrosMouseClicked

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        // TODO add your handling code here:
        if (txtNomeMonstro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Nome não pode estar em branco!","Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (comboTipo.getSelectedItem().equals("Selecionar")) {
            JOptionPane.showMessageDialog(null, "Campo Tipo precisa ter um valor válido!","Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (txtClasseDeArmadura1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Classe de Armadura não pode estar em branco!","Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (txtPontosDeVida.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Pontos de Vida não pode estar em branco!","Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (txtPontosDeVidaAtual.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Pontos de Vida Atual não pode estar em branco!","Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (txtDeslocamento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Deslocamento não pode estar em branco!","Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (txtNivelDesafio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Nível de Desafio não pode estar em branco!","Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            repositorioMonstros.setNomeMonstro(txtNomeMonstro.getText());
            repositorioMonstros.setTipo((String) comboTipo.getSelectedItem());
            repositorioMonstros.setClasseDeArmadura(Integer.parseInt(txtClasseDeArmadura1.getText()));
            repositorioMonstros.setPontosDeVida(txtPontosDeVida.getText());
            repositorioMonstros.setPontosDeVidaAtual(Integer.parseInt(txtPontosDeVidaAtual.getText()));
            repositorioMonstros.setDeslocamento(txtDeslocamento.getText());
            repositorioMonstros.setNivelDeDesafio(txtNivelDesafio.getText());
            repositorioMonstros.setReferencia(txtReferencia.getText());
            repositorioMonstros.setIdRepositorioMonstros(Integer.parseInt(txtIdentificador.getText()));

            repositorioMonstroDao.editarMonstros(repositorioMonstros);
        }
        limparCampos();
        atualizarTabela();
    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        int opcao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Excluir este Monstro?", "Exclusão de Monstro", JOptionPane.YES_NO_OPTION);
        if (opcao == 0) {
            String nome = txtNomeMonstro.getText();
            repositorioMonstroDao.excluirMonstros(nome);

        }
        atualizarTabela();
        limparCampos();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void txtPesquisarMonstrosPorNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarMonstrosPorNomeKeyPressed
        // TODO add your handling code here:
        String pesquisar = txtPesquisarMonstrosPorNome.getText();
        tabelaPesquisaMonstros.setModel(new TabelaModeloRepositorioMonstros(new RepositorioMonstroDao().listarRepositorioMonstroPorNome(pesquisar)));
    }//GEN-LAST:event_txtPesquisarMonstrosPorNomeKeyPressed

    public void limparCampos() {
        txtIdentificador.setText("");
        txtNomeMonstro.setText("");
        comboTipo.setSelectedItem("Selecionar");
        txtClasseDeArmadura1.setText("");
        txtPontosDeVida.setText("");
        txtPontosDeVidaAtual.setText("");
        txtDeslocamento.setText("");
        txtNivelDesafio.setText("");
        txtReferencia.setText("");
        btEditar.setEnabled(false);
        btExcluir.setEnabled(false);
    }

    public void atualizarTabela() {
        tabelaPesquisaMonstros.setModel(new TabelaModeloRepositorioMonstros(new RepositorioMonstroDao().listarMonstros()));
    }

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroMonstros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroMonstros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroMonstros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroMonstros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroMonstros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimparTela;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedMonstros;
    private javax.swing.JTable tabelaPesquisaMonstros;
    private javax.swing.JTextField txtClasseDeArmadura1;
    private javax.swing.JTextField txtDeslocamento;
    private javax.swing.JTextField txtIdentificador;
    private javax.swing.JTextField txtNivelDesafio;
    private javax.swing.JTextField txtNomeMonstro;
    private javax.swing.JTextField txtPesquisarMonstrosPorNome;
    private javax.swing.JTextField txtPontosDeVida;
    private javax.swing.JTextField txtPontosDeVidaAtual;
    private javax.swing.JTextField txtReferencia;
    // End of variables declaration//GEN-END:variables
}
