/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mcg.view;

import br.com.mcg.dao.ClasseDePersonagemDao;
import br.com.mcg.dao.PersonagemDao;
import br.com.mcg.dao.RacaDePersonagemDao;
import br.com.mcg.model.ClasseDePersonagem;
import br.com.mcg.model.Personagem;
import br.com.mcg.model.RacaDePersonagem;
import br.com.mcg.tabelaDeModelos.TabelaModeloPersonagens;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author alafaria
 */
public class TelaCadastroPersonagem extends javax.swing.JFrame {
    
    Personagem personagem = new Personagem();
    PersonagemDao personagemDao = new PersonagemDao();
    /**
     * Creates new form TelaCadastroPersonagem
     */
    public TelaCadastroPersonagem() {
        initComponents();
        setIconImage(getToolkit().createImage(getClass().getResource("/icones/icone_principal.png")));
        TabelaPersonagens.setModel(new TabelaModeloPersonagens(new PersonagemDao().listarPersonagem()));
        btExcluir.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPersonagens = new javax.swing.JTabbedPane();
        panelPersonagem = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIdentificador = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        labelClasse = new javax.swing.JLabel();
        comboClasse = new javax.swing.JComboBox<>();
        labelRaca = new javax.swing.JLabel();
        comboRaca = new javax.swing.JComboBox<>();
        labelDadosDeVida = new javax.swing.JLabel();
        comboDadosDeVida = new javax.swing.JComboBox<>();
        labelTotalPontosVida = new javax.swing.JLabel();
        txtTotalPontosDeVida = new javax.swing.JTextField();
        labelPontosVidaAtual = new javax.swing.JLabel();
        txtPontosDeVidaAtual = new javax.swing.JTextField();
        labelPontosExperiencia = new javax.swing.JLabel();
        txtPontosDeExperiencia = new javax.swing.JTextField();
        labelPontosHeroicos = new javax.swing.JLabel();
        txtPontosHeroicos = new javax.swing.JTextField();
        labelNivel = new javax.swing.JLabel();
        comboNivel = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelConsultaPersonagem = new javax.swing.JPanel();
        labelNome1 = new javax.swing.JLabel();
        txtPesquisarPersonagemPorNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaPersonagens = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCadastrarClasse = new javax.swing.JMenuItem();
        menuCadastrarRaca = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCadastrarDados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Master Control Guide - Cadastro de Personagem");

        jTabbedPersonagens.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPersonagens.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Identificador:");

        txtIdentificador.setEditable(false);
        txtIdentificador.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        labelNome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelNome.setForeground(new java.awt.Color(0, 0, 102));
        labelNome.setText("Nome:");

        txtNome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        labelClasse.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelClasse.setForeground(new java.awt.Color(0, 0, 102));
        labelClasse.setText("Classe:");

        comboClasse.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        comboClasse.setForeground(new java.awt.Color(0, 0, 102));
        comboClasse.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                comboClasseAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        labelRaca.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelRaca.setForeground(new java.awt.Color(0, 0, 102));
        labelRaca.setText("Raça:");

        comboRaca.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        comboRaca.setForeground(new java.awt.Color(0, 0, 102));
        comboRaca.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                comboRacaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        labelDadosDeVida.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelDadosDeVida.setForeground(new java.awt.Color(0, 0, 102));
        labelDadosDeVida.setText("Dados de Vida:");

        comboDadosDeVida.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        comboDadosDeVida.setForeground(new java.awt.Color(0, 0, 102));
        comboDadosDeVida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 D 6", "1 D 8", "1 D 10", "1 D 12" }));
        comboDadosDeVida.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                comboDadosDeVidaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        labelTotalPontosVida.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelTotalPontosVida.setForeground(new java.awt.Color(0, 0, 102));
        labelTotalPontosVida.setText("Total de Pontos de Vida:");

        txtTotalPontosDeVida.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        labelPontosVidaAtual.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelPontosVidaAtual.setForeground(new java.awt.Color(0, 0, 102));
        labelPontosVidaAtual.setText("Pontos de Vida Atual:");

        txtPontosDeVidaAtual.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        labelPontosExperiencia.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelPontosExperiencia.setForeground(new java.awt.Color(0, 0, 102));
        labelPontosExperiencia.setText("Pontos de Experiência:");

        txtPontosDeExperiencia.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        labelPontosHeroicos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelPontosHeroicos.setForeground(new java.awt.Color(0, 0, 102));
        labelPontosHeroicos.setText("Pontos Heróicos:");

        txtPontosHeroicos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        labelNivel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelNivel.setForeground(new java.awt.Color(0, 0, 102));
        labelNivel.setText("Nível do Personagem:");

        comboNivel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        comboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telaPersonagem.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelPersonagemLayout = new javax.swing.GroupLayout(panelPersonagem);
        panelPersonagem.setLayout(panelPersonagemLayout);
        panelPersonagemLayout.setHorizontalGroup(
            panelPersonagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPersonagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPersonagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelPersonagemLayout.createSequentialGroup()
                            .addGroup(panelPersonagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelNome)
                                .addComponent(jLabel2))
                            .addGap(103, 103, 103)
                            .addGroup(panelPersonagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNome)
                                .addGroup(panelPersonagemLayout.createSequentialGroup()
                                    .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(panelPersonagemLayout.createSequentialGroup()
                            .addComponent(labelClasse)
                            .addGap(155, 155, 155)
                            .addGroup(panelPersonagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPontosDeVidaAtual, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboDadosDeVida, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboClasse, javax.swing.GroupLayout.Alignment.LEADING, 0, 172, Short.MAX_VALUE))
                            .addGap(28, 28, 28)
                            .addGroup(panelPersonagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelTotalPontosVida)
                                .addGroup(panelPersonagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTotalPontosDeVida, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPersonagemLayout.createSequentialGroup()
                                        .addGroup(panelPersonagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelPontosExperiencia)
                                            .addComponent(labelPontosHeroicos))
                                        .addGap(32, 32, 32)
                                        .addGroup(panelPersonagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPontosHeroicos, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                            .addComponent(txtPontosDeExperiencia)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPersonagemLayout.createSequentialGroup()
                                        .addComponent(labelRaca)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                        .addComponent(comboRaca, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(labelDadosDeVida)
                    .addComponent(labelPontosVidaAtual)
                    .addGroup(panelPersonagemLayout.createSequentialGroup()
                        .addComponent(labelNivel)
                        .addGap(41, 41, 41)
                        .addComponent(comboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        panelPersonagemLayout.setVerticalGroup(
            panelPersonagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonagemLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelPersonagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPersonagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPersonagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRaca, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPersonagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelClasse)
                        .addComponent(comboClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPersonagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPersonagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelDadosDeVida)
                        .addComponent(comboDadosDeVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelTotalPontosVida)
                    .addComponent(txtTotalPontosDeVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPersonagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPontosDeVidaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPersonagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelPontosVidaAtual)
                        .addComponent(labelPontosExperiencia)
                        .addComponent(txtPontosDeExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPersonagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNivel)
                    .addComponent(comboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPontosHeroicos)
                    .addComponent(txtPontosHeroicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPersonagemLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPersonagens.addTab("Personagens", panelPersonagem);

        labelNome1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelNome1.setForeground(new java.awt.Color(0, 0, 102));
        labelNome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pesquisar.png"))); // NOI18N
        labelNome1.setText("Pesquisar Personagem por Nome:");

        txtPesquisarPersonagemPorNome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtPesquisarPersonagemPorNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarPersonagemPorNomeKeyPressed(evt);
            }
        });

        TabelaPersonagens.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        TabelaPersonagens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TabelaPersonagens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaPersonagensMouseClicked(evt);
            }
        });
        TabelaPersonagens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TabelaPersonagensKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaPersonagens);

        javax.swing.GroupLayout panelConsultaPersonagemLayout = new javax.swing.GroupLayout(panelConsultaPersonagem);
        panelConsultaPersonagem.setLayout(panelConsultaPersonagemLayout);
        panelConsultaPersonagemLayout.setHorizontalGroup(
            panelConsultaPersonagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaPersonagemLayout.createSequentialGroup()
                .addGroup(panelConsultaPersonagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConsultaPersonagemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelNome1)
                        .addGap(18, 18, 18)
                        .addComponent(txtPesquisarPersonagemPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelConsultaPersonagemLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 976, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        panelConsultaPersonagemLayout.setVerticalGroup(
            panelConsultaPersonagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaPersonagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConsultaPersonagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome1)
                    .addComponent(txtPesquisarPersonagemPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jTabbedPersonagens.addTab("Consulta de Personagens", panelConsultaPersonagem);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));
        jPanel1.setForeground(new java.awt.Color(0, 51, 102));
        jPanel1.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Personagens");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        btCadastrar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btCadastrar.setForeground(new java.awt.Color(0, 51, 153));
        btCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/salvar.png"))); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btEditar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btEditar.setForeground(new java.awt.Color(0, 51, 153));
        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/editar.png"))); // NOI18N
        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btExcluir.setForeground(new java.awt.Color(0, 51, 153));
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/excluir_1.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btSair.setForeground(new java.awt.Color(0, 51, 153));
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sair.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 51, 153));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/limparCampos.png"))); // NOI18N
        jButton5.setText("Limpar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/utilitarios.png"))); // NOI18N
        jMenu1.setText("Personagem");

        menuCadastrarClasse.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        menuCadastrarClasse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/classe_32.png"))); // NOI18N
        menuCadastrarClasse.setText("Cadastrar Classe de Personagem");
        menuCadastrarClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarClasseActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadastrarClasse);

        menuCadastrarRaca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
        menuCadastrarRaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/orc_32.png"))); // NOI18N
        menuCadastrarRaca.setText("Cadastrar Raça de Personagem");
        menuCadastrarRaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarRacaActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadastrarRaca);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Dice_48.png"))); // NOI18N
        jMenu2.setText("Dados");

        menuCadastrarDados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastrarDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/dice.png"))); // NOI18N
        menuCadastrarDados.setText("Rolagem de Dados");
        menuCadastrarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarDadosActionPerformed(evt);
            }
        });
        jMenu2.add(menuCadastrarDados);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(btEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jTabbedPersonagens, javax.swing.GroupLayout.PREFERRED_SIZE, 1048, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btCadastrar, btEditar, btExcluir, btSair, jButton5});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jTabbedPersonagens, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btCadastrar)
                        .addComponent(btEditar)
                        .addComponent(btExcluir)
                        .addComponent(btSair))
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btCadastrar, btEditar, btExcluir, btSair, jButton5});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboClasseAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_comboClasseAncestorAdded
        // TODO add your handling code here:
        ClasseDePersonagemDao classeDePersonagemDao = new ClasseDePersonagemDao();
        List<ClasseDePersonagem> listaDeClasses = classeDePersonagemDao.listarClasse();
        comboClasse.removeAll();

        for (ClasseDePersonagem cdp : listaDeClasses) {
            comboClasse.addItem(String.valueOf(cdp));
        }
    }//GEN-LAST:event_comboClasseAncestorAdded

    private void comboRacaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_comboRacaAncestorAdded
        // TODO add your handling code here:
        RacaDePersonagemDao racaDePersonagemDao = new RacaDePersonagemDao();
        List<RacaDePersonagem> listaDeRacas = racaDePersonagemDao.listarRaca();
        comboRaca.removeAll();

        for (RacaDePersonagem rdp : listaDeRacas) {
            comboRaca.addItem(String.valueOf(rdp));
        }
    }//GEN-LAST:event_comboRacaAncestorAdded

    private void menuCadastrarClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarClasseActionPerformed
        // TODO add your handling code here:
        TelaCadastrarClasse telaCadastrarClasse = new TelaCadastrarClasse();
        telaCadastrarClasse.setVisible(true);
        telaCadastrarClasse.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuCadastrarClasseActionPerformed

    private void menuCadastrarRacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarRacaActionPerformed
        // TODO add your handling code here:
        TelaCadastrarRaca telaCadastrarRaca = new TelaCadastrarRaca();
        telaCadastrarRaca.setVisible(true);
        telaCadastrarRaca.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuCadastrarRacaActionPerformed

    private void comboDadosDeVidaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_comboDadosDeVidaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDadosDeVidaAncestorAdded

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:
       if(txtNome.getText().isEmpty() || comboClasse.getSelectedItem().equals("") || comboRaca.getSelectedItem().equals("") || comboDadosDeVida.getSelectedItem().equals("") || txtPontosDeVidaAtual.getText().isEmpty() || txtTotalPontosDeVida.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Os campos NOME, CLASSE, RAÇA, DADOS DE VIDA, PONTOS DE VIDA e PONTOS DE VIDA ATUAL não podem estar vazios.","Atenção", JOptionPane.WARNING_MESSAGE);
       }else{
           personagem.setNome(txtNome.getText());
           personagem.setClasse((String) comboClasse.getSelectedItem());
           personagem.setRaca((String) comboRaca.getSelectedItem());
           personagem.setDadosDeVida((String) comboDadosDeVida.getSelectedItem());
           personagem.setTotalPontosVida(Integer.parseInt(txtTotalPontosDeVida.getText()));
           personagem.setPontosVidaAtual(Integer.parseInt(txtPontosDeVidaAtual.getText()));
           personagem.setPontosDeExperiencia(Integer.parseInt(txtPontosDeExperiencia.getText()));
           personagem.setNivel(Integer.parseInt((String)comboNivel.getSelectedItem()));
           personagem.setPontoHeroico(Integer.parseInt(txtPontosHeroicos.getText()));
           personagem.setSituacao("Em Combate");
           
           personagemDao.adicionarPersonagem(personagem);
       }
       limparTela();
       atualizarTabelaPersonagem();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void TabelaPersonagensKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TabelaPersonagensKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TabelaPersonagensKeyPressed

    private void TabelaPersonagensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaPersonagensMouseClicked
        // TODO add your handling code here:
        jTabbedPersonagens.setSelectedIndex(0);
        txtIdentificador.setText(TabelaPersonagens.getValueAt(TabelaPersonagens.getSelectedRow(), TabelaModeloPersonagens.COLUNA_CODIGO).toString());
        txtNome.setText(TabelaPersonagens.getValueAt(TabelaPersonagens.getSelectedRow(), TabelaModeloPersonagens.COLUNA_NOME).toString());
        comboClasse.setSelectedItem(TabelaPersonagens.getValueAt(TabelaPersonagens.getSelectedRow(), TabelaModeloPersonagens.COLUNA_CLASSE).toString());
        comboRaca.setSelectedItem(TabelaPersonagens.getValueAt(TabelaPersonagens.getSelectedRow(), TabelaModeloPersonagens.COLUNA_RACA).toString());
        comboDadosDeVida.setSelectedItem(TabelaPersonagens.getValueAt(TabelaPersonagens.getSelectedRow(), TabelaModeloPersonagens.COLUNA_DADOS_VIDA).toString());
        txtTotalPontosDeVida.setText(TabelaPersonagens.getValueAt(TabelaPersonagens.getSelectedRow(), TabelaModeloPersonagens.COLUNA_TOTAL_PONTOS_VIDA).toString());
        txtPontosDeVidaAtual.setText(TabelaPersonagens.getValueAt(TabelaPersonagens.getSelectedRow(), TabelaModeloPersonagens.COLUNA_PONTOS_VIDA_ATUAL).toString());
        txtPontosDeExperiencia.setText(TabelaPersonagens.getValueAt(TabelaPersonagens.getSelectedRow(), TabelaModeloPersonagens.COLUNA_PONTOS_EXPERIENCIA).toString());
        comboNivel.setSelectedItem(TabelaPersonagens.getValueAt(TabelaPersonagens.getSelectedRow(), TabelaModeloPersonagens.COLUNA_NIVEL).toString());
        txtPontosHeroicos.setText(TabelaPersonagens.getValueAt(TabelaPersonagens.getSelectedRow(), TabelaModeloPersonagens.COLUNA_PONTO_HEROICO).toString());
        btExcluir.setEnabled(true);
        
    }//GEN-LAST:event_TabelaPersonagensMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        limparTela();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        // TODO add your handling code here:
        if(txtNome.getText().isEmpty() || comboClasse.getSelectedItem().equals("") || comboRaca.getSelectedItem().equals("") || comboDadosDeVida.getSelectedItem().equals("") || txtPontosDeVidaAtual.getText().isEmpty() || txtTotalPontosDeVida.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Os campos NOME, CLASSE, RAÇA, DADOS DE VIDA, PONTOS DE VIDA e PONTOS DE VIDA ATUAL não podem estar vazios.","Atenção", JOptionPane.WARNING_MESSAGE);
            }else{
                personagem.setNome(txtNome.getText());
                personagem.setClasse((String) comboClasse.getSelectedItem());
                personagem.setRaca((String) comboRaca.getSelectedItem());
                personagem.setDadosDeVida((String) comboDadosDeVida.getSelectedItem());
                personagem.setTotalPontosVida(Integer.parseInt(txtTotalPontosDeVida.getText()));
                personagem.setPontosVidaAtual(Integer.parseInt(txtPontosDeVidaAtual.getText()));
                personagem.setPontosDeExperiencia(Integer.parseInt(txtPontosDeExperiencia.getText()));
                personagem.setNivel(Integer.parseInt((String) comboNivel.getSelectedItem()));
                personagem.setPontoHeroico(Integer.parseInt(txtPontosHeroicos.getText()));
                personagem.setPersonagemId(Integer.parseInt(txtIdentificador.getText()));
                personagemDao.editarPersonagem(personagem);
            }
        atualizarTabelaPersonagem();
        limparTela();
        btExcluir.setEnabled(false);
    }//GEN-LAST:event_btEditarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        int opcao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Excluir este Personagem?", "Exclusão de Personagem", JOptionPane.YES_NO_OPTION);
        if (opcao == 0){
            String nome = txtNome.getText();
            personagemDao.excluirPersonagem(nome);
            atualizarTabelaPersonagem();
            limparTela();
        }
        btExcluir.setEnabled(false);
    }//GEN-LAST:event_btExcluirActionPerformed

    private void menuCadastrarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarDadosActionPerformed
        // TODO add your handling code here:
        TelaRolagemDados telaRolagemDados = new TelaRolagemDados();
        telaRolagemDados.setVisible(true);
        telaRolagemDados.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuCadastrarDadosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPesquisarPersonagemPorNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarPersonagemPorNomeKeyPressed
        // TODO add your handling code here:
        String pesquisar = txtPesquisarPersonagemPorNome.getText();
        TabelaPersonagens.setModel(new TabelaModeloPersonagens(new PersonagemDao().listarPersonagemPorNome(pesquisar)));
    }//GEN-LAST:event_txtPesquisarPersonagemPorNomeKeyPressed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPersonagem



.class  


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPersonagem



.class  


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPersonagem



.class  


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPersonagem



.class  


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroPersonagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaPersonagens;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox<String> comboClasse;
    private javax.swing.JComboBox<String> comboDadosDeVida;
    private javax.swing.JComboBox<String> comboNivel;
    private javax.swing.JComboBox<String> comboRaca;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPersonagens;
    private javax.swing.JLabel labelClasse;
    private javax.swing.JLabel labelDadosDeVida;
    private javax.swing.JLabel labelNivel;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNome1;
    private javax.swing.JLabel labelPontosExperiencia;
    private javax.swing.JLabel labelPontosHeroicos;
    private javax.swing.JLabel labelPontosVidaAtual;
    private javax.swing.JLabel labelRaca;
    private javax.swing.JLabel labelTotalPontosVida;
    private javax.swing.JMenuItem menuCadastrarClasse;
    private javax.swing.JMenuItem menuCadastrarDados;
    private javax.swing.JMenuItem menuCadastrarRaca;
    private javax.swing.JPanel panelConsultaPersonagem;
    private javax.swing.JPanel panelPersonagem;
    private javax.swing.JTextField txtIdentificador;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisarPersonagemPorNome;
    private javax.swing.JTextField txtPontosDeExperiencia;
    private javax.swing.JTextField txtPontosDeVidaAtual;
    private javax.swing.JTextField txtPontosHeroicos;
    private javax.swing.JTextField txtTotalPontosDeVida;
    // End of variables declaration//GEN-END:variables

    private void limparTela() {
        txtIdentificador.setText("");
        txtNome.setText("");
        comboClasse.setSelectedItem("Bárbaro");
        comboRaca.setSelectedItem("Anão");
        comboDadosDeVida.setSelectedItem("1 D 6");
        txtTotalPontosDeVida.setText("");
        txtPontosDeVidaAtual.setText("");
        txtPontosDeExperiencia.setText("");
        comboNivel.setSelectedItem("1");
        txtPontosHeroicos.setText("");
    }

    private void atualizarTabelaPersonagem() {
        TabelaPersonagens.setModel(new TabelaModeloPersonagens(new PersonagemDao().listarPersonagem()));
    }
}
